### ISSUE TITLE
Doesn't detect RDF on aksw.org

### ISSUE THREAD

**Issue by white-gecko** [AKSW/LDOW2016_PF_Client#5]
Using the AnnotationClient on aksw.org doesn't work, since it doesn't detect the correct location of the RDF, even though it is given with the following link tag:

```
 <link
        rel="foaf:primaryTopic"
        href="http://aksw.org/About" />
```

There is also an alternate given.

```
<link rel="alternate" type="application/rdf+xml" href="http://aksw.org/About.rdf" />
```

The current feature branch with the correct jQuery is:

https://github.com/AKSW/aksw.org/tree/feature/StructuredFeedback

**Comment by rmeissn** [comment]
That's right for now. We're searching for

```
<link rel="alternate" type="application/json" href="http://......./....json" />
```

Since we're not using any library to parse triples (because [N3](https://www.npmjs.com/package/n3) was full of bugs), we can only parse RDF+JSON.

A request for content-negotiation is also a good idea, but takes some time to implement. Especially for all those failure cases that will be newly introduced by different handling of DBpedia compared to the rest of the world.

**Comment by white-gecko** [comment]
Hm, still doesn't work.

**Comment by white-gecko** [comment]
The content negotiation (resp. request) should be done somehow like this:

```
   var jsonURL = $('link[rel="alternate"][type="application/rdf+json"]').attr('href');
   // get jsonURI
   var resourceURL = FBE.extractResourceUrl();
   // content negotiation on resourceURI with Accept: application/rdf+json;q=1.0, application/json;q=0.8
   var jsonURL = $('link[rel="alternate"][type="application/json"]').attr('href');
   // get jsonURI and see if it is rdf
```
